version: "3.8"

services:
  esig-api:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    working_dir: /app
    environment:
      # SMTP Configuration
      - SMTP_HOST=${SMTP_HOST}
      - SMTP_PORT=${SMTP_PORT}
      - SMTP_USER=${SMTP_USER}
      - SMTP_PASS=${SMTP_PASS}
      
      # Application Configuration
      - APP_URL=${APP_URL}
      - APP_ENV=${APP_ENV}
      
      # API Configuration
      - API_RATE_LIMIT=${API_RATE_LIMIT}
      - WEB_RATE_LIMIT=${WEB_RATE_LIMIT}
      
      # Security
      - SESSION_LIFETIME=${SESSION_LIFETIME}
      - CSRF_TOKEN_EXPIRY=${CSRF_TOKEN_EXPIRY}
    env_file:
      - .env
    command: php -S 0.0.0.0:8000 -t src/
    networks:
      - esignature-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/status"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

networks:
  esignature-network:
    driver: bridge
